BEGIN;
CREATE TABLE dbo.cleaned_api_data (
    id INT,
    user_id INT,
    emp_id INT,
    team_manager_id INT,
    designation_id INT,
    designation_name VARCHAR(100),
    first_name VARCHAR(50),
    middle_name VARCHAR(50),
    last_name VARCHAR(50),
    email VARCHAR(100),
    is_hr BOOLEAN,
    is_supervisor BOOLEAN,
    leave_issuer_id DOUBLE PRECISION,
    issuer_first_name VARCHAR(50),
    issuer_middle_name VARCHAR(50),
    issuer_last_name VARCHAR(50),
    current_leave_issuer_id DOUBLE PRECISION,
    current_leave_issuer_email VARCHAR(100),
    department_description VARCHAR(100),
    start_date TIMESTAMP,
    end_date TIMESTAMP,
    leave_days INT,
    reason TEXT,
    leave_status VARCHAR(50),
    status VARCHAR(50),
    response_remarks TEXT,
    leave_type_id INT,
    leave_type VARCHAR(50),
    default_days INT,
    transferable_days INT,
    is_consecutive BOOLEAN,
    fiscal_id INT,
    fiscal_start_date TIMESTAMP,
    fiscal_end_date TIMESTAMP,
    fiscal_is_current BOOLEAN,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    is_automated BOOLEAN,
    is_converted BOOLEAN,
    total_count INT,
    allocations TEXT
);

COMMIT;